defmodule ProGen.MixProject do
  use Mix.Project

  @version "0.0.3"
  @source_url "https://github.com/andyl/pro_gen"

  def project do
    [
      app: :pro_gen,
      version: @version,
      elixir: "~> 1.19",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      usage_rules: usage_rules(),
      deps: deps(),
      # Documentation
      name: "ProGen",
      source_url: @source_url,
      homepage_url: @source_url,
      source_ref: "v#{@version}",
      aliases: aliases(),
      docs: [
        main: "overview",
        logo: "assets/logo.svg",
        favicon: "assets/favicon.svg",
        source_ref: "master",
        extras: [
          {"README.md", title: "Overview", filename: "overview"},
          "guides/example_scripts.md",
          "guides/composite_actions.md",
          "LICENSE.txt"
        ],
        assets: %{"assets" => "assets"},
        before_closing_body_tag: %{
          html: """
          <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
          <script>
            document.addEventListener("DOMContentLoaded", function () {
              mermaid.initialize({startOnLoad: false, theme: "default"});
              let id = 0;
              for (const codeEl of document.querySelectorAll("pre code.mermaid")) {
                const preEl = codeEl.parentElement;
                const graphDefinition = codeEl.textContent;
                const graphEl = document.createElement("div");
                const graphId = "mermaid-graph-" + id++;
                mermaid.render(graphId, graphDefinition).then(function(result) {
                  graphEl.innerHTML = result.svg;
                  preEl.insertAdjacentElement("afterend", graphEl);
                  preEl.remove();
                });
              }
            });
          </script>
          """
        }
      ]
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp aliases do
    [
      docgen: [&generate_script_guide/1, &reload_and_docs/1]
    ]
  end

  defp generate_script_guide(_) do
    Mix.Task.run("compile")
    ProGen.Xt.ScriptGuide.generate()
  end

  # Force Mix to re-read project/0 so the :extras list
  # picks up the guide generated by docs.scripts.
  defp reload_and_docs(_) do
    Mix.Project.pop()
    Mix.Project.push(__MODULE__)
    Mix.Task.rerun("docs")
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp usage_rules do
    [
      file: "RULES.md",
      usage_rules: [{~r/.*/, link: :markdown}],
      skills: [
        location: ".claude/skills",
        build: []
      ]
    ]
  end

  defp deps do
    [
      {:git_ops, "~> 2.0", only: [:dev, :test], runtime: false},
      {:igniter, "~> 0.6"},
      {:sourceror, "~> 1.11"},
      {:usage_rules, "~> 1.0"},
      {:nimble_options, "~> 1.0"},
      {:optimus, "~> 0.5"},
      {:yaml_elixir, "~> 2.11"},
      {:ex_doc, "~> 0.31", only: :dev, runtime: false},
      {:commit_hook, "~> 0.4", only: :dev, runtime: false}
    ]
  end
end
