defmodule ProGen.MixProject do
  use Mix.Project

  @version "0.0.1"
  @source_url "https://github.com/andyl/pro_gen"

  def project do
    [
      app: :pro_gen,
      version: @version,
      elixir: "~> 1.19",
      start_permanent: Mix.env() == :prod,
      usage_rules: usage_rules(),
      deps: deps(),
      # Documentation
      name: "ProGen",
      source_url: @source_url,
      homepage_url: @source_url,
      source_ref: "v#{@version}",
      aliases: aliases(),
      docs: [
        main: "overview",
        logo: "assets/logo.svg",
        favicon: "assets/favicon.svg",
        source_ref: "master",
        extras: [
          {"README.md", title: "Overview", filename: "overview"},
          "guides/example_scripts.md",
          "LICENSE.txt",
        ],
        assets: %{"assets" => "assets"}
      ]
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp aliases do
    [
      docgen: ["docs.scripts", &reload_and_docs/1]
    ]
  end

  # Force Mix to re-read project/0 so the :extras list
  # picks up the guide generated by docs.scripts.
  defp reload_and_docs(_) do
    Mix.Project.pop()
    Mix.Project.push(__MODULE__)
    Mix.Task.rerun("docs")
  end

  defp usage_rules do
    [
      file: "RULES.md",
      usage_rules: [{~r/.*/, link: :markdown}],
      skills: [
        location: ".claude/skills",
        build: []
      ]
    ]
  end

  defp deps do
    [
      {:igniter, "~> 0.6"},
      {:sourceror, "~> 1.11"},
      {:usage_rules, "~> 1.0"},
      {:nimble_options, "~> 1.0"},
      {:optimus, "~> 0.5"},
      {:ex_doc, "~> 0.31", only: :dev, runtime: false}
    ]
  end
end
