defmodule ProGen.Script do
  @moduledoc """
  Functions for ProGen scripts.

    * `cli_args/1`    — Store an Optimus schema in ProGen.Env
    * `cli_args/0`    — Retrieve the stored Optimus schema
    * `parse_args/2`  — Parse argv against an Optimus schema
    * `parse_args/1`  — Parse argv using the stored schema
    * `parse_args/0`  — Parse System.argv() using the stored schema
    * `cli_vals/0`    — Retrieve the parsed CLI values
    * `usage/1`       — Generate help text from an Optimus schema
    * `usage/0`       — Generate help text from the stored schema
    * `command/2,3`   — Print description then run a system command (auto-commits by default)
    * `action/3`      — Run a ProGen action (auto-commits by default)
    * `validate/3`    — Run a ProGen validator
    * `puts/1`        — Print a formatted message
    * `log/1`         — Log an info message
    * `start/1`       — Log a start message and record the start time
    * `finish/1`      — Log a finish message with elapsed time
    * `cd/1`          — Change the working directory
    * `clear/0`       — Clear the screen

  Usage Example:

  ```
  #!/usr/bin/env elixir

  Mix.install([:pro_gen, github: "andyl/pro_gen"])

  alias ProGen.Script, as: PS

  PS.puts "Hello World"
  ...
  ```

  # --- Schema storage ---

  @doc \"""
  Stores an Optimus schema in `ProGen.Env` under `:pg_cli_args`.
  """
  def cli_args(schema) do
    ProGen.Env.put(:pg_cli_args, schema)
  end

  @doc """
  Retrieves the Optimus schema previously stored by `cli_args/1`.
  """
  def cli_args do
    ProGen.Env.get(:pg_cli_args)
  end

  @doc """
  Retrieves the cli values generated by `parse_args`.
  """
  def cli_vals do
    ProGen.Env.get(:pg_cli_vals)
  end

  # --- CLI parsing ---

  @doc """
  Parses `argv` (list or string) against an explicit Optimus `schema`.

  Returns `{:ok, %Optimus.ParseResult{}}`, `{:error, errors}`, `:help`, or `:version`.
  """
  def parse_args(schema, argv) when is_binary(argv),
    do: parse_args(schema, String.split(argv))

  def parse_args(schema, argv) when is_list(argv) do
    optimus = Optimus.new!(schema)
    Optimus.parse(optimus, argv)
  end

  @doc """
  Parses `argv` using the schema stored by `cli_args/1`.

  On success, merges `parsed.args`, `parsed.options`, and `parsed.flags` into
  a single flat map and stores it in `ProGen.Env` under `:pg_cli_vals`.

  Returns `{:ok, merged_map}`, `{:error, errors}`, `:help`, or `:version`.
  On `:help`, auto-prints usage. On `:version`, auto-prints the version string.
  """
  def parse_args(argv) when is_list(argv) or is_binary(argv) do
    schema = cli_args()

    case parse_args(schema, argv) do
      {:ok, parsed} ->
        merged = Map.merge(parsed.args, Map.merge(parsed.options, parsed.flags))
        ProGen.Env.put(:pg_cli_vals, merged)
        {:ok, merged}

      :help ->
        usage() |> IO.puts()
        :help

      :version ->
        IO.puts(schema[:version] || "unknown")
        :version

      {:error, errors} ->
        IO.puts(:stderr, "\nError:")

        errors
        |> List.wrap()
        |> Enum.each(&IO.puts(:stderr, "- #{&1}"))

        IO.puts(:stderr, "")
        usage() |> IO.puts()
        do_halt(1)
    end
  end

  @doc """
  Parses `System.argv()` using the stored schema. Convenience for `parse_args(System.argv())`.
  """
  def parse_args do
    parse_args(System.argv())
  end

  @doc """
  Generates help text from an explicit Optimus `schema`.
  """
  def usage(schema) when is_list(schema) do
    optimus = Optimus.new!(schema)
    Optimus.help(optimus)
  end

  @doc """
  Generates help text from the schema stored by `cli_args/1`.
  """
  def usage do
    usage(cli_args())
  end

  # --- DSL functions ---

  @doc """
  Prints a formatted description, then runs a system command via `ProGen.Sys.cmd/1`.

  Auto-commits after a successful command unless `commit: false` is passed.
  """
  def command(desc, command, opts \\ []) do
    {commit_opts, _rest} = Keyword.split(opts, [:commit])

    log(desc)
    IO.puts(command)

    result =
      ProGen.Sys.cmd(command)
      |> halt_on_error()

    auto_commit(desc, "chore(command)", commit_opts)
    result
  end

  @doc """
  Runs a ProGen action.

  Accepts either a string name (looked up in the `ProGen.Actions` registry)
  or a module atom (used directly after verifying it implements `ProGen.Action`).

  `opts` can be a keyword list (passed through) or a bare list, in which case
  it is auto-wrapped under the action's single required list option key.
  For example, `action("desc", "validate", [:has_mix])` becomes
  `Actions.run("validate", checks: [:has_mix])`.
  """
  def action(desc, name_or_mod, opts \\ [])

  def action(desc, mod, opts) when is_atom(mod) do
    {commit_opts, action_opts} = Keyword.split(opts, [:commit])

    log(desc)

    result =
      mod
      |> ProGen.Actions.run(action_opts)
      |> halt_on_error()

    auto_commit(desc, mod.commit_type(), commit_opts)
    result
  end

  def action(desc, action_name, opts) do
    {commit_opts, action_opts} = Keyword.split(opts, [:commit])

    log(desc)

    commit_type =
      case ProGen.Actions.action_module(action_name) do
        {:ok, mod} -> mod.commit_type()
        :error -> "chore(action)"
      end

    result =
      action_name
      |> ProGen.Actions.run(normalize_action_opts(action_name, action_opts))
      |> halt_on_error()

    auto_commit(desc, commit_type, commit_opts)
    result
  end

  @doc """
  Runs a ProGen validator.

  Accepts either a string name (looked up in the `ProGen.Validations` registry)
  or a module atom (used directly). Runs the given list of checks and halts on
  the first failure.
  """
  def validate(desc, name_or_mod, checks \\ [])

  def validate(desc, mod, checks) when is_atom(mod) do
    log(desc)

    mod
    |> ProGen.Validations.run(checks: checks)
    |> halt_on_error()
  end

  def validate(desc, validator_name, checks) do
    log(desc)

    validator_name
    |> ProGen.Validations.run(checks: checks)
    |> halt_on_error()
  end

  # ----- output functions

  @doc """
  Prints a formatted message prefixed with `>>>`.
  """
  def puts(text) do
    text
    |> String.trim_trailing()
    |> String.split("\n")
    |> Enum.each(fn line ->
      output = IO.ANSI.color(208) <> line <> IO.ANSI.reset()
      IO.puts("> #{output}")
    end)
  end

  @doc """
  Inspect an elixir term.
  """
  def inspect(text, term, _opts \\ []) do
    puts(text)
    IO.inspect(term)
  end

  @doc """
  Prints an error message.
  """
  def err(text) when is_binary(text), do: err_puts(text)
  def err(term), do: term |> inspect() |> err_puts()

  def err_puts(text) do
    output = IO.ANSI.light_red() <> text <> IO.ANSI.reset()
    IO.puts("Error: #{output}")
  end

  @doc """
  Logs an info-level message via `Logger`.
  """
  def log(text) do
    require Logger
    Logger.info(IO.ANSI.light_yellow() <> text <> IO.ANSI.reset())
    Logger.flush()
  end

  @doc """
  Logs a start message and records the start time in `:pg_start_time`.
  """
  def start(message \\ "START") do
    now = NaiveDateTime.local_now()
    timestamp = Calendar.strftime(now, "%y%m%d_%H%M%S")
    ProGen.Env.put(:pg_start_time, now)
    ProGen.Env.put(:pg_start_timestamp, timestamp)
    log(message)
  end

  @doc """
  Logs a finish message with elapsed time and records the finish time
  in `:pg_finish_time` and elapsed time in `:pg_elapsed_time`.
  """
  def finish(message \\ "FINISH") do
    now = NaiveDateTime.local_now()
    timestamp = Calendar.strftime(now, "%y%m%d_%H%M%S")
    ProGen.Env.put(:pg_finish_time, now)
    ProGen.Env.put(:pg_finish_timestamp, timestamp)

    elapsed =
      case ProGen.Env.get(:pg_start_time) do
        nil ->
          "00h 00m 00s"

        start_time ->
          diff = NaiveDateTime.diff(now, start_time, :second)
          hours = div(diff, 3600)
          minutes = diff |> rem(3600) |> div(60)
          seconds = rem(diff, 60)

          :io_lib.format("~2..0Bh ~2..0Bm ~2..0Bs", [hours, minutes, seconds])
          |> IO.iodata_to_binary()
      end

    ProGen.Env.put(:pg_elapsed_time, elapsed)
    log(message <> " (elapsed time #{elapsed})")
  end

  @doc """
  Changes the working directory of the BEAM process.
  All subsequent commands will run in the new directory.
  """
  def cd(dir) do
    log("CD #{dir}")
    File.cd!(dir)
  end

  @doc """
  Clears the terminal screen.
  """
  def clear do
    IO.write(IO.ANSI.clear() <> IO.ANSI.home())
  end

  # --- String Conversion Utility ---

  def to_pascal_case(string) when is_binary(string) do
    string
    |> String.split("_")
    |> Enum.map_join(&String.capitalize/1)
  end

  # --- Private helpers ---

  defp auto_commit(desc, commit_type, opts) do
    ProGen.Xtool.AutoCommit.auto_commit(desc, commit_type, opts)
  end

  defp normalize_action_opts(action_name, opts) do
    if Keyword.keyword?(opts) do
      opts
    else
      case ProGen.Actions.action_module(action_name) do
        {:ok, mod} ->
          required_list_keys =
            for {key, config} <- mod.opts_def(),
                config[:required] == true,
                match?({:list, _}, config[:type]),
                do: key

          case required_list_keys do
            [key] -> [{key, opts}]
            _ -> opts
          end

        :error ->
          opts
      end
    end
  end

  defp halt_on_error(:ok), do: :ok

  defp halt_on_error({:ok, :skipped}) do
    IO.puts("skipped...")
    :ok
  end

  defp halt_on_error({:error, message}) do
    err(message)
    do_halt(1)
  end

  defp do_halt(code) do
    halt_fn = Application.get_env(:pro_gen, :system_halt, &System.halt/1)
    halt_fn.(code)
  end
end
